### ISSUE TITLE
Create Milestone

### ISSUE THREAD

**Issue by leaofelipe** [Sintropia/team-hub-core-api#8]
- [x] Create Model
  - date Date Start
  - date Date End
  - string Name
  - FK teamId

**Create Routes**
- [x] POST /milestones
- [x] DELETE /milestones
- [x] PATCH /milestones/:id
- [x] GET /milestones/:id
- [x] GET /teams/:id/milestones
